<?php
// @todo in install

function pagerer_install() {
  menu_rebuild();    
//  db_query("UPDATE {system} SET weight = 255 WHERE name = 'pagerer'");
  // @todo ???? + help 
  $t = get_t();
  drupal_set_message($t('The Pagerer module has been installed. Visit <a href="@url">module help</a> for instructions.',
                     array('@url' => url('admin/help/pagerer'))));
}

function pagerer_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'pagerer%'");
  cache_clear_all('variables', 'cache');
}