<?php
/**
 * @file
 * Pagerer install
 *
 * Pagerer installation hooks.
 *
 * Backdrop core 1.x
 *
 * @package  User interface
 * @author   mondrake <mondrake@mondrake.org>
 */

/**
 * Implements hook_install().
 */
function pagerer_install() {
  $t = get_t();
  backdrop_set_message(
    $t(
      'The Pagerer module has been installed. Visit <a href="@url">configure</a> for configuration.',
      array('@url' => url('admin/config/user-interface/pagerer'))
    )
  );
  // Dynamically generated variable data was detected on the following lines.
  // /pagerer/pagerer.module line 2026
}

/**
 * Implements hook_uninstall().
 */
function pagerer_uninstall() {
  // Remove all variables whose name begins with 'pagerer'.
  $res = db_select('variable', 'v')
      ->fields('v')
      ->condition('name', 'pagerer%', 'LIKE')
      ->execute();
  if ($res) {
    foreach ($res as $row) {
      // TODO This variable was probably removed in Backdrop without replacement.
      variable_del($row->name);
      backdrop_set_message(t('Variable %var has been deleted.', array('%var' => $row->name)));
    }
  }
}

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function pagerer_update_7100() { }

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function pagerer_update_7101() { }

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function pagerer_update_7102() { }

/**
 * Implements hook_update_last_removed().
 */
function pagerer_update_last_removed() {
  return 7102;
}

/**
 * Migrate pagerer variables to config.
 */
function pagerer_update_1000() {
  $config = config('pagerer.settings');
  $config->set('pagerer', update_variable_get('pagerer', array()));
  $config->set('pagererpresetpreset_name', update_variable_get('pagererpresetpreset_name', 'dynamic variable in file /pagerer/pagerer.module line 2026'));
  $config->save();

  update_variable_del('pagerer');
  update_variable_del('pagererpresetpreset_name');
}
