<?php
/**
 * @file
 * A Drupal front-end for mondrake.
 *
 * More soon...
 */

function _pagerer_tags_merge_default($theme, $tags = null)
{
    switch($theme) {
    case 'pagerer_mini':
        $default_tags = array(
            'first'           => '«',
            'previous'        => '<',
            'next'            => '>',
            'last'            => '»',
            'label'           => 'Page',
            'pager_breaker'   => t('…'),
            'pager_separator' => t('&nbsp'),
            'range_separator' => t('-'),
            'range_of'        => t('of '),
        );
        break;
    case 'pagerer_progressive':
        $default_tags = array(
            'first'           => '@num',
            'previous'        => '-@num',
            'next'            => '+@num›',
            'last'            => '@num»',
            'label'           => null,
            'pager_breaker'   => t(':'),
            'pager_separator' => t('|'),
            'range_separator' => t('-'),
            'range_of'        => t('of'),
        );
        break;
    default:
        $default_tags = array(
            'first'           => '« first',
            'previous'        => '‹ previous @num',
            'next'            => 'next @num›',
            'last'            => 'last »',
            'label'           => null,
            'pager_breaker'   => t('…'),
            'pager_separator' => t('&nbsp'),
            'range_separator' => t('-'),
            'range_of'        => t('of'),
        );
        break;
    }
    if ($tags) {
        return array_merge($default_tags, $tags);
    } else {
        return $default_tags;
    }
}

function _pagerer_resolve_markers($variables)
{
    $element = $variables['element'];
    $parameters = $variables['parameters'];
    $quantity = $variables['quantity'];
    global $pager_page_array, $pager_total, $pager_total_items, $pager_limits;
    
    // Calculate various markers

    $markers = array();
    
    // Pages

    // Middle is used to "center" pages around the current page.
    $markers['pager_middle'] = ceil($quantity / 2);
    // current is the page we are currently paged to
    $markers['pager_current'] = $pager_page_array[$element] + 1;
    // first is the first page listed by this pager piece (re quantity)
    $markers['pager_first'] = $markers['pager_current'] - $markers['pager_middle'] + 1;
    // last is the last page listed by this pager piece (re quantity)
    $markers['pager_last'] = $markers['pager_current'] + $quantity - $markers['pager_middle'];
    // max is the maximum page number
    $markers['pager_max'] = $pager_total[$element];

    // Items

    // pager_current_first_item is the first item listed on the current page
    $markers['pager_current_first_item'] = $pager_limits[$element] * $pager_page_array[$element] + 1;
    // pager_current_last_item is the last item listed by this pager piece
    $markers['pager_current_last_item'] = 
        ($pager_limits[$element] * $markers['pager_current']) > $pager_total_items[$element] ? 
        $pager_total_items[$element] : 
        $pager_limits[$element] * $markers['pager_current'];
    // pager_item_max is the maximum item number
    $markers['pager_item_max'] = $pager_total_items[$element];
    // pager_items_next is the number of items expected on next page
    if ($markers['pager_current'] * $pager_limits[$element] > $markers['pager_item_max']) {
        $markers['pager_items_next'] = null;
    } else {
        $markers['pager_items_next'] = 
            $pager_total_items[$element] - ($markers['pager_current'] * $pager_limits[$element]) > $pager_limits[$element] ? 
            $pager_limits[$element] : 
            $pager_total_items[$element] - ($markers['pager_current'] * $pager_limits[$element]);
    }
    // pager_item_previous is the number of items expected on previous page
    if ($markers['pager_current'] == 1) {
        $markers['pager_items_previous'] = null;
    } else {
        $markers['pager_items_previous'] = $pager_limits[$element];
    }

    // End of marker calculations.
    
    return $markers;
}

function _pagerer_get_left_links($variables, $markers)
{
    $items_prev = $variables['display'] <> 'pages' ? $markers['pager_items_previous'] : null;
    
    $li_first = theme(
        'pager_first', 
        array(
            'text' => t($variables['tags']['first']), 
            'element' => $variables['element'], 
            'parameters' => $variables['parameters'],
        )
    );
    $li_previous = theme(
        'pager_previous', 
        array(
            'text' => t($variables['tags']['previous'], array('@num' => $items_prev)), 
            'element' => $variables['element'], 
            'interval' => 1, 
            'parameters' => $variables['parameters'],
        )
    );

    $items = array();
    if ($variables['left_links'] <> 'never') {
        if ($li_first or $variables['left_links'] == 'always') {
            $items[] = array(
                'class' => array('pager-first'),
                'data' => $li_first ? $li_first : t($variables['tags']['first']),
            );
            $items[] = array(
                'class' => array('pager-item'),
                'data' => $variables['tags']['pager_separator'],
            );
        }
        if ($li_previous or $variables['left_links'] == 'always') {
            $items[] = array(
                'class' => array('pager-previous'),
                'data' => $li_previous ? $li_previous : t($variables['tags']['previous'], array('@num' => $items_prev)),
            );
            $items[] = array(
                'class' => array('pager-item'),
                'data' => $variables['tags']['pager_separator'],
            );
        }
    }
    return $items;
}

function _pagerer_get_right_links($variables, $markers)
{
    $items_next = $variables['display'] <> 'pages' ? $markers['pager_items_next'] : null;
    
    $li_next = theme(
        'pager_next', 
        array(
            'text' => t($variables['tags']['next'], array('@num' => $items_next)), 
            'element' => $variables['element'], 
            'interval' => 1, 
            'parameters' => $variables['parameters']
        )
    );
    
    $li_last = theme(
        'pager_last', 
        array(
            'text' => t($variables['tags']['last']), 
            'element' => $variables['element'], 
            'parameters' => $variables['parameters']
        )
    );

    $items = array();
    if ($variables['right_links'] <> 'never') {
        if ($li_next or $variables['right_links'] == 'always') {
            $items[] = array(
                'class' => array('pager-item'),
                'data' => $variables['tags']['pager_separator'],
            );
            $items[] = array(
                'class' => array('pager-next'),
                'data' => $li_next ? $li_next : t($variables['tags']['next'], array('@num' => $items_next)),
            );
        }
        if ($li_last or $variables['right_links'] == 'always') {
            $items[] = array(
                'class' => array('pager-item'),
                'data' => $variables['tags']['pager_separator'],
            );
            $items[] = array(
                'class' => array('pager-last'),
                'data' => $li_last ? $li_last : t($variables['tags']['last']),
            );
        }
    }
    return $items;
}

/**
 * Implements hook_theme().
 */
function pagerer_theme()
{
    // @todo incorporate common tags
    $commonTheme = drupal_common_theme();
    $theme = array(
        'pagerer' => array(
            'variables' => array(
                'tags'         => _pagerer_tags_merge_default('pagerer'),
                'element'      => $commonTheme['pager']['variables']['element'],
                'parameters'   => $commonTheme['pager']['variables']['parameters'],
                'quantity'     => $commonTheme['pager']['variables']['quantity'],
            ),
        ),
        'pagerer_std' => array(
            'variables' => array(
                'tags'         => _pagerer_tags_merge_default('pagerer_std'),
                'element'      => $commonTheme['pager']['variables']['element'],
                'parameters'   => $commonTheme['pager']['variables']['parameters'],
                'quantity'     => $commonTheme['pager']['variables']['quantity'],
                'display'      => 'pages',             // pages|items|item_ranges
                'left_links'   => 'not_on_first',      // not_on_first|always|never
                'right_links'  => 'not_on_last',       // not_on_last|always|never
            ),
        ),
        'pagerer_progressive' => array(
            'variables' => array(
                'tags'         => _pagerer_tags_merge_default('pagerer_std'),
                'element'      => $commonTheme['pager']['variables']['element'],
                'parameters'   => $commonTheme['pager']['variables']['parameters'],
                'quantity'     => $commonTheme['pager']['variables']['quantity'],
                'display'      => 'pages',             // pages|items|item_ranges
                'left_links'   => 'not_on_first',      // not_on_first|always|never
                'right_links'  => 'not_on_last',       // not_on_last|always|never
            ),
        ),
        'pagerer_mini' => array(
            'variables' => array(
                'tags'         => _pagerer_tags_merge_default('pagerer_mini'),
                'element'      => $commonTheme['pager']['variables']['element'],
                'parameters'   => $commonTheme['pager']['variables']['parameters'],
                'quantity'     => $commonTheme['pager']['variables']['quantity'],
                'display'      => 'pages',
                'left_links'   => 'always',
                'right_links'  => 'always',
            ),
        ),
    );
    return $theme;
}

/**
 * This is pagerer's wrapper for overriden standard 'pager' theme calls
 */
function theme_pagerer($variables)
{ 
    drupal_add_css(drupal_get_path('module', 'pagerer') .'/pagerer.css');
    
    // table
    $rows = array();
    $row = array();
    $variables['tags'] = array();

    unset($variables['left_links']);  
    unset($variables['right_links']);
    $variables['display'] = 'items';
    $variables['tags']['label'] = t('Item');
    //$cell1 = array( 'data' => theme('pagerer_mini', $variables), 'class' => array('pagerer', 'pagerer-left'), );
    //$cell1 = null;

    $variables['display'] = 'pages';
    $variables['left_links'] = 'never';  
    $variables['right_links'] = 'never';
    $variables['quantity'] = 5;
    $cell1 = array( 'data' => theme('pagerer_progressive', $variables), 'class' => array('pagerer', 'pagerer-left'), );
    $cell2 = null;

    unset($variables['left_links']);
    unset($variables['right_links']);
    $variables['display'] = 'pages';
    $variables['tags']['label'] = t('Page');
    $cell3 = array( 'data' => theme('pagerer_mini', $variables), 'class' => array('pagerer', 'pagerer-right'), );

    $row = array(
        'data' => array(
            $cell1,
            $cell2,
            $cell3,
        ),
        'no_striping' => true,
    );
    $rows[] = $row;
        
    $output = theme_table(array(
        'header' => array(),
        'rows' => $rows,
        'attributes' => array( 'class' => array('pagerer',), ),
        'caption' => null,
        'colgroups' => null,
        'sticky' => false,
        'empty' => null,
    ));
    
    return $output;
}

/**
 * This is the standard pager + extensions
 */
function theme_pagerer_std($variables)
{ 
    global $pager_page_array, $pager_total, $pager_total_items, $pager_limits;
    $element = $variables['element'];

    // Check if pager is needed; if not, return immediately
    if ($pager_total[$element] == 1 and $variables['left_links'] <> 'always' and $variables['right_links'] <> 'always') {
        return null;
    }

    $tags = $variables['tags'] = _pagerer_tags_merge_default('pagerer_std', $variables['tags']);
    $parameters = $variables['parameters'];
    $quantity = $variables['quantity'];

    // Calculate various markers within this pager piece:
    $markers = _pagerer_resolve_markers($variables);

    // Prepare for generation loop.
    $i = $markers['pager_first'];
    if ($markers['pager_last'] > $markers['pager_max']) {
    // Adjust "center" if at end of query.
        $i = $i + ($markers['pager_max'] - $markers['pager_last']);
        $markers['pager_last'] = $markers['pager_max'];
    }
    if ($i <= 0) {
    // Adjust "center" if at start of query.
        $markers['pager_last'] = $markers['pager_last'] + (1 - $i);
        $i = 1;
    }
    // End of generation loop preparation.

    // left links
    $items = _pagerer_get_left_links($variables, $markers);
    // When there is more than one page, create the pager list.
    if ($i != $markers['pager_max']) {
        if ($i > 1) {
            $items[] = array(
                'class' => array('pager-ellipsis'),
                'data' => $tags['pager_breaker'],
            );
            $items[] = array(
                'class' => array('pager-item'),
                'data' => $tags['pager_separator'],
            );
        }
        
        // Now generate the actual pager piece.
        for (; $i <= $markers['pager_last'] && $i <= $markers['pager_max']; $i++) {

            switch ($variables['display']) {
            case 'items':
                $display = (($i - 1) * $pager_limits[$element]) + 1;
                break;
            case 'item_ranges':
                $display = ((($i - 1) * $pager_limits[$element]) + 1) . $tags['range_separator'] . ($i * $pager_limits[$element]);
                break;
            case 'pages':
            default:
                $display = $i;
                break;
            }
            
            if ($i < $markers['pager_current']) {
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => theme('pager_previous', array('text' => $display, 'element' => $element, 'interval' => ($markers['pager_current'] - $i), 'parameters' => $parameters)),
                );
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => $tags['pager_separator'],
                );
            }
            if ($i == $markers['pager_current']) {
                $items[] = array(
                    'class' => array('pager-current'),
                    'data' => $display,
                );
                if ($i != $markers['pager_max']) {
                    $items[] = array(
                        'class' => array('pager-item'),
                        'data' => $tags['pager_separator'],
                    );
                }
            }
            if ($i > $markers['pager_current']) {
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => theme('pager_next', array('text' => $display, 'element' => $element, 'interval' => ($i - $markers['pager_current']), 'parameters' => $parameters)),
                );
                if ($i != $markers['pager_max']) {
                    $items[] = array(
                        'class' => array('pager-item'),
                        'data' => $tags['pager_separator'],
                    );
                }
            }
        }

        if ($i <= $markers['pager_max']) {
            $items[] = array(
                'class' => array('pager-ellipsis'),
                'data' => $tags['pager_breaker'],
            );
        }
    }   
    // right links
    $items = array_merge($items, _pagerer_get_right_links($variables, $markers));
    // End generation.
    
    
    return '<h2 class="element-invisible">' . t('Pages') . '</h2>' . theme('item_list', array(
        'items' => $items,
        'attributes' => array('class' => array('pager')),
    ));
}

function theme_pagerer_progressive($variables)
{ 
    global $pager_page_array, $pager_total, $pager_total_items, $pager_limits;
    $element = $variables['element'];

    // Check if pager is needed; if not, return immediately
    if ($pager_total[$element] == 1 and $variables['left_links'] <> 'always' and $variables['right_links'] <> 'always') {
        return null;
    }

    $tags = $variables['tags'] = _pagerer_tags_merge_default('pagerer_progressive', $variables['tags']);
    $parameters = $variables['parameters'];
    $quantity = $variables['quantity'];

    // Calculate various markers within this pager piece:
    $markers = _pagerer_resolve_markers($variables);

    // Prepare for generation loop.
    $i = $markers['pager_first'];
    if ($markers['pager_last'] > $markers['pager_max']) {
    // Adjust "center" if at end of query.
        $i = $i + ($markers['pager_max'] - $markers['pager_last']);
        $markers['pager_last'] = $markers['pager_max'];
    }
    if ($i <= 0) {
    // Adjust "center" if at start of query.
        $markers['pager_last'] = $markers['pager_last'] + (1 - $i);
        $i = 1;
    }
    // End of generation loop preparation.

    // left links
    $items = _pagerer_get_left_links($variables, $markers);
    // When there is more than one page, create the pager list.
    if ($i != $markers['pager_max']) {
        if ($i > 1) {
            $items[] = array(
                'class' => array('pager-ellipsis'),
                'data' => $tags['pager_breaker'],
            );
            $items[] = array(
                'class' => array('pager-item'),
                'data' => $tags['pager_separator'],
            );
        }
        
        // Now generate the actual pager piece.
        for (; $i <= $markers['pager_last'] && $i <= $markers['pager_max']; $i++) {

            switch ($variables['display']) {
            case 'items':
                $display = (($i - 1) * $pager_limits[$element]) + 1;
                break;
            case 'item_ranges':
                $display = ((($i - 1) * $pager_limits[$element]) + 1) . $tags['range_separator'] . ($i * $pager_limits[$element]);
                break;
            case 'pages':
            default:
                $display = $i;
                break;
            }
            
            if ($i < $markers['pager_current']) {
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => theme('pager_previous', array('text' => $display, 'element' => $element, 'interval' => ($markers['pager_current'] - $i), 'parameters' => $parameters)),
                );
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => $tags['pager_separator'],
                );
            }
            if ($i == $markers['pager_current']) {
                $items[] = array(
                    'class' => array('pager-current'),
                    'data' => $display,
                );
                if ($i != $markers['pager_max']) {
                    $items[] = array(
                        'class' => array('pager-item'),
                        'data' => $tags['pager_separator'],
                    );
                }
            }
            if ($i > $markers['pager_current']) {
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => theme('pager_next', array('text' => $display, 'element' => $element, 'interval' => ($i - $markers['pager_current']), 'parameters' => $parameters)),
                );
                if ($i != $markers['pager_max']) {
                    $items[] = array(
                        'class' => array('pager-item'),
                        'data' => $tags['pager_separator'],
                    );
                }
            }
        }

        if ($i <= $markers['pager_max']) {
            $items[] = array(
                'class' => array('pager-ellipsis'),
                'data' => $tags['pager_breaker'],
            );
        }
    }   
    // right links
    $items = array_merge($items, _pagerer_get_right_links($variables, $markers));
    // End generation.
    
    
    return '<h2 class="element-invisible">' . t('Pages') . '</h2>' . theme('item_list', array(
        'items' => $items,
        'attributes' => array('class' => array('pager')),
    ));


/*    $output = theme('pagerer_std', $variables);
    $tags = $variables['tags'] = _pagerer_tags_merge_default('pagerer_progressive', $variables['tags']);
    $markers = _pagerer_resolve_markers($variables);
    
    // Prepare for generation loop.
    $i = $markers['pager_first'];
    if ($markers['pager_last'] > $markers['pager_max']) {
    // Adjust "center" if at end of query.
        $i = $i + ($markers['pager_max'] - $markers['pager_last']);
        $markers['pager_last'] = $markers['pager_max'];
    }
    if ($i <= 0) {
    // Adjust "center" if at start of query.
        $markers['pager_last'] = $markers['pager_last'] + (1 - $i);
        $i = 1;
    }

    $items = array();
//    kpr($markers);
    for (; $i <= $markers['pager_last'] && $i <= $markers['pager_max']; $i++) {
        $items[$i - 1]['interval'] = $i - $markers['pager_current'];
        $items[$i - 1]['display'] = $i;
    }
    // r ratio
    // a scale factor
    $inc = 0;
    $c = $markers['pager_current'] - 1;
    for ($i = 0; ; $i++) {
        $inc = intval(pow(10, $i));
        if ($c + $inc < $markers['pager_max']) {
            $items[$c + $inc]['interval'] = $inc;
            $items[$c + $inc]['display'] = $c + $inc + 1;
        } else {
            break;
        }
    }
    $inc = 0;
    $c = $markers['pager_current'] - 1;
    for ($i = 0; ; $i++) {
        $inc = intval(2.5 * pow(10, $i));
        if ($c + $inc < $markers['pager_max']) {
            $items[$c + $inc]['interval'] = $inc;
            $items[$c + $inc]['display'] = $c + $inc + 1;
        } else {
            break;
        }
    }
    $inc = 0;
    $c = $markers['pager_current'] - 1;
    for ($i = 0; ; $i++) {
        $inc = intval(5 * pow(10, $i));
        if ($c + $inc < $markers['pager_max']) {
            $items[$c + $inc]['interval'] = $inc;
            $items[$c + $inc]['display'] = $c + $inc + 1;
        } else {
            break;
        }
    }
    asort($items);

/*    $output .= theme('item_list', array(
      'items' => $items,
    ));
    kpr($items);

    return $output;*/
}

/**
* This is the standard pager + extensions
*/
function theme_pagerer_mini($variables)
{ 
    global $pager_total;
    $element = $variables['element'];

    // Check if pager is needed; if not, return immediately
    if ($pager_total[$element] == 1 and $variables['left_links'] <> 'always' and $variables['right_links'] <> 'always') {
        return null;
    }

    // resolve default tags 
    $variables['tags'] = _pagerer_tags_merge_default('pagerer_mini', $variables['tags']);
    
    // Calculate various markers within this pager piece:
    $markers = _pagerer_resolve_markers($variables);

    // left links
    $items = _pagerer_get_left_links($variables, $markers);
    // label
    $items[] = array(
      'class' => array('pager-item'),
      'data' => $variables['tags']['label'],
    );
    // current page
    $items[] = array(
       'class' => array('pager-item'),
       //'data' => $i,
       'data' => pagerer_drpager_widget($variables, $markers),
    );
    // range of
    $items[] = array(
      'class' => array('pager-item'),
      'data' => $variables['tags']['range_of'] . ($variables['display'] <> 'pages' ? $markers['pager_item_max'] : $markers['pager_max']),
    );
    // right links
    $items = array_merge($items, _pagerer_get_right_links($variables, $markers));

    return '<h2 class="element-invisible">' . t('Pages') . '</h2>' . theme('item_list', array(
      'items' => $items,
      'attributes' => array('class' => array('pager')),
    ));
}

function pagerer_drpager_widget($variables, $markers) {
    drupal_add_css(drupal_get_path('module', 'pagerer') .'/pagerer.css');
    drupal_add_js(drupal_get_path('module', 'pagerer') .'/drpager.js');  

    // construct the query string exactly like the pager
    // @todo what to do with $parameters??
    global $pager_page_array, $pager_total, $pager_total_items, $pager_limits;
    $element = $variables['element'];
    $parameters = $variables['parameters'];
    
    if ($variables['display'] == 'pages') {
        $curr = $markers['pager_current'];
        $max = $markers['pager_max'];
        $interval = 1;
    } else {
        $curr = $markers['pager_current_first_item'];
        $max = $markers['pager_item_max'];
        $interval = $pager_limits[$element];
    }    
    
    $page_new = pager_load_array($markers['pager_current'] - 1, $element, $pager_page_array);
    $page_new[$element] = 'drpagerpage';
    $parameters['page'] = implode(',', $page_new);
    $queryParameters = pager_get_query_parameters();
    array_merge($parameters, $queryParameters);

    $url = url($_GET['q'], array('query' => $parameters,));
    // @todo improve  
    $url = substr($url, 7);
    $state = drupal_json_encode(array(
        'url' => $url, 
        'element' => $element, 
        'total' => $max, 
        'interval' => $interval, 
        'display' => $variables['display']
    ));
    $title = t('Set page number to go to, then press enter');
    return "<input type=\"text\" class=\"drpager-page\" name ='$state' title=\"$title\" value=\"$curr\" />";
}

