<?php
/**
 * @file
 * Pagerer install
 *
 * Pagerer installation hooks.
 *
 */

/**
 * Implements hook_install().
 */
function pagerer_install() {
  backdrop_set_message(t('The Pagerer module has been installed. Visit <a href="@url">configure</a> for configuration.', array(
    '@url' => url('admin/config/user-interface/pagerer'),
  )));
}

/**
 * Implements hook_uninstall().
 */
function pagerer_uninstall() {
  // Remove the module's configuration.
  config('pagerer.settings')->delete();
}

/**
 * Implements hook_update_last_removed().
 */
function pagerer_update_last_removed() {
  return 7102;
}

/**
 * Migrate pagerer variables to config.
 */
function pagerer_update_1000() {
  $config = config('pagerer.settings');
  $config->set('pagerer.general', update_variable_get('pagerer', array()));
  $config->save();

  update_variable_del('pagerer');

  // 'pagerer_preset_name' was a Drupal 7 variable that is no longer used;
  // its presets are now individually keyed under 'pagerer.preset.*'.
  update_variable_del('pagerer_preset_name');
}
