<?php
/**
 * @file
 * Pagerer
 *
 * A set of pager themes to enhance on Drupal standard pager.
 *
 * Drupal core 7.x
 *
 * @package  User interface
 * @author   mondrake <mondrake@mondrake.org>
 */

/**
 * Implements hook_theme().
 */
function pagerer_theme() {
    $common_theme = drupal_common_theme();
    $theme = array(
      'pagerer' => array(
        'variables' => array(
          'tags'            => _pagerer_tags_merge_default('pagerer'),
          'element'         => $common_theme['pager']['variables']['element'],
          'parameters'      => $common_theme['pager']['variables']['parameters'],
          'quantity'        => $common_theme['pager']['variables']['quantity'],
        ),
      ),
      'pagerer_standard' => array(
        'variables' => array(
          'tags'            => _pagerer_tags_merge_default('pagerer_standard'),
          'element'         => $common_theme['pager']['variables']['element'],
          'parameters'      => $common_theme['pager']['variables']['parameters'],
          'quantity'        => $common_theme['pager']['variables']['quantity'],
          // pages|items|item_ranges
          'display'         => 'pages',
          // none|before_current|left|right
          'label_display'   => 'none',
          // none|normal|widget
          'current_display' => 'normal',
          // none|after_current|left|right
          'max_display'     => 'none',
          // not_on_first|always|never
          'first_link'      => 'not_on_first',
          // not_on_first|always|never
          'previous_link'   => 'not_on_first',
          // not_on_last|always|never
          'next_link'       => 'not_on_last',
          // not_on_last|always|never
          'last_link'       => 'not_on_last',
          // absolute|relative
          'progr_links'     => 'absolute',
        ),
      ),
      'pagerer_progressive' => array(
        'variables' => array(
          'tags'            => _pagerer_tags_merge_default('pagerer_progressive'),
          'element'         => $common_theme['pager']['variables']['element'],
          'parameters'      => $common_theme['pager']['variables']['parameters'],
          'quantity'        => 5,
          'display'         => 'pages',
          'label_display'   => 'none',
          'current_display' => 'normal',
          'max_display'     => 'none',
          'first_link'      => 'never',
          'previous_link'   => 'never',
          'next_link'       => 'never',
          'last_link'       => 'never',
          'progr_links'     => 'relative',
          // Comma delimited string of factors to use.
          'factors'         => '2.5,5,10',
        ),
      ),
      'pagerer_adaptive' => array(
        'variables' => array(
          'tags'            => _pagerer_tags_merge_default('pagerer_adaptive'),
          'element'         => $common_theme['pager']['variables']['element'],
          'parameters'      => $common_theme['pager']['variables']['parameters'],
          'quantity'        => 5,
          'display'         => 'pages',
          'label_display'   => 'none',
          'current_display' => 'normal',
          'max_display'     => 'none',
          'first_link'      => 'never',
          'previous_link'   => 'never',
          'next_link'       => 'never',
          'last_link'       => 'never',
          'progr_links'     => 'relative',
        ),
      ),
      'pagerer_mini' => array(
        'variables' => array(
          'tags'            => _pagerer_tags_merge_default('pagerer_mini'),
          'element'         => $common_theme['pager']['variables']['element'],
          'parameters'      => $common_theme['pager']['variables']['parameters'],
          'quantity'        => $common_theme['pager']['variables']['quantity'],
          'display'         => 'pages',
          'label_display'   => 'before_current',
          'current_display' => 'widget',
          'max_display'     => 'after_current',
          'first_link'      => 'always',
          'previous_link'   => 'always',
          'next_link'       => 'always',
          'last_link'       => 'always',
          'progr_links'     => 'relative',
        ),
      ),
    );
    return $theme;
}

/**
 * De
 */
function _pagerer_tags_merge_default($theme, $tags = NULL) {
  switch ($theme) {
    case 'pagerer_standard':
        $default_tags = array(
          'first'           => '« first',
          'previous'        => '‹ previous',
          'next'            => 'next ›',
          'last'            => 'last »',
          'max'             => t('of @pages'),
          'previous_progr'  => '‹ previous',
          'next_progr'      => 'next ›',
          'label'           => 'Pages:',
          'pager_breaker'   => t('…'),
          'pager_separator' => t('&nbsp'),
          'range_separator' => t('-'),
        );
      break;
    case 'pagerer_mini':
        $default_tags = array(
          'first'           => '«',
          'previous'        => '<',
          'next'            => '>',
          'last'            => '»',
          'max'             => t('of @pages'),
          'previous_progr'  => '-',
          'next_progr'      => '+',
          'label'           => 'Page',
          'pager_breaker'   => t('…'),
          'pager_separator' => t('&nbsp'),
          'range_separator' => t('-'),
        );
      break;
    default:
        $default_tags = array(
          'first'           => '« @num',
          'previous'        => '‹ @num',
          'next'            => '@num ›',
          'last'            => '@num »',
          'max'             => t('of @pages'),
          'previous_progr'  => '-@num',
          'next_progr'      => '+@num',
          'label'           => 'Pages:',
          'pager_breaker'   => t('…'),
          'pager_separator' => t('&nbsp'),
          'range_separator' => t('-'),
        );
      break;
  }
  if ($tags) {
    return array_merge($default_tags, $tags);
  }
  else {
    return $default_tags;
  }
}

/**
 * This is Pagerer's wrapper for overriden standard 'pager' theme calls
 */
function theme_pagerer($variables) {
  global $pager_total, $pager_limits;

  // Check if pager is needed; if not, return immediately.
  if ($pager_total[$variables['element']] == 1 or $pager_total[$variables['element']] == 0) {
    return NULL;
  }

  // Prepare table row.
  $rows = array();
  $row = array();
  $variables['tags'] = array();


  $variables['display'] = 'pages';
  // $variables['current_display'] = 'widget';
  $variables['quantity'] = 5;
  $variables['progr_links'] = 'relative';

  // $variables[''] = 'always';
  // $variables[''] = 'always';
  $cell1 = array('data' => theme('pagerer_adaptive', $variables), 'class' => array('pagerer', 'pagerer-left'));
  $cell2 = NULL;
  unset($variables['first_link']);
  unset($variables['previous_link']);
  unset($variables['next_link']);
  unset($variables['last_link']);
  $variables['display'] = 'pages';
  // $variables['tags']['label'] = t('Item');
  $cell3 = array('data' => theme('pagerer_mini', $variables), 'class' => array('pagerer', 'pagerer-right'));

  $row = array(
    'data' => array(
      $cell1,
      $cell2,
      $cell3,
    ),
    'no_striping' => TRUE,
  );
  $rows[] = $row;

  $output = theme_table(array(
      'header' => array(),
      'rows' => $rows,
      'attributes' => array('class' => array('pagerer')),
      'caption' => NULL,
      'colgroups' => NULL,
      'sticky' => FALSE,
      'empty' => NULL,
  ));

  return $output;
}

/**
 * This theme is alike standard Drupal pager theme.
 *
 * Provides links to the 'neigborhood' of current page, plus first/previous
 * /next/last page. Extended control on the pager is available through
 * Pagerer's specific $variables.
 */
function theme_pagerer_standard($variables) {
  return _pagerer_theme_handler('pagerer_standard', $variables);
}

/**
 * This theme provides links to pages progressively more distant from current.
 *
 * Besides links to the 'neigborhood' of current page, creates a list of links
 * which are progressively more distant from current page, displaying either a
 * page number or an offset from current page.
 *
 * This is controlled via the 'progr_links' theme variable, which can take a
 * value either 'absolute' or 'relative'.
 *
 * Examples:
 *
 * page 9 out of 212, progr_links 'absolute', display 'pages':
 * -----------------------------------------------------------------------------------------
 * 1  ... 4  ...  7  8  [9]  10  11  ... 14  ...  19  ...  59  ... 109  ... 212
 * -----------------------------------------------------------------------------------------
 *
 * page 9 out of 212, progr_links 'relative', display 'pages':
 * -----------------------------------------------------------------------------------------
 * 1  ... -5  ...  7  8  [9]  10  11  ...  +5  ...  +10  ... +50  ... +100  ... 212
 * -----------------------------------------------------------------------------------------
 *
 * The 'factors' theme variable controls the quantity of progressive links
 * generated. Each value in the comma delimited string will be used as a
 * scale factor for a progressive series of pow(10, n).
 *
 * Examples:
 * 'factors' => '10'    will generate links for page offsets
 *
 *                      ..., -1000, -100, -10, 10, 100, 1000, ....
 *
 * 'factors' => '5,10'  will generate links for page offsets
 *
 *                      ..., -1000, -500, -100, -50, -10, -5, 5, 10, 50, 100, 500, 1000, ....
 *
 * etc.
 */
function theme_pagerer_progressive($variables) {
  return _pagerer_theme_handler('pagerer_progressive', $variables);
}

/**
 * This is the standard pager + extensions
 */
function theme_pagerer_adaptive($variables) {
  return _pagerer_theme_handler('pagerer_adaptive', $variables);
}

/**
 * This theme displays current page (or item) within the range.
 *
 * Examples:
 *
 * page 9 out of 955, display 'pages':
 * -----------------------------------------------------------
 * «  <  Page 9 of 955  >  »
 * -----------------------------------------------------------
 *
 * page 9 out of 955, total items = 47731, limit = 50, display = 'items':
 * -----------------------------------------------------------
 * «  <  Item 401 of 47731  >  »
 * -----------------------------------------------------------
 */
function theme_pagerer_mini($variables) {
  return _pagerer_theme_handler('pagerer_mini', $variables);
}

/**
 * Pagerer's theme handler.
 *
 * Calls to any theme_pagerer_xxx() function are channeled to this handler.
 *
 * @param string $theme
 *   theme name
 * @param array  $variables
 *   theme's variables
 *
 * @return string
 *   HTML item list
 */
function _pagerer_theme_handler($theme, $variables) {
  global $pager_total, $pager_limits;

  // Check if pager is needed; if not, return immediately.
  if (($pager_total[$variables['element']] == 1 or $pager_total[$variables['element']] == 0)
        and $variables['first_link'] <> 'always'
        and $variables['previous_link'] <> 'always'
        and $variables['next_link'] <> 'always'
        and $variables['last_link'] <> 'always') {
    return NULL;
  }
  // Add Pagerer's css.
  drupal_add_css(drupal_get_path('module', 'pagerer') . '/pagerer.css');
  // Resolve default tags.
  $variables['tags'] = _pagerer_tags_merge_default($theme, $variables['tags']);
  // Resolve markers.
  $markers = _pagerer_resolve_markers($variables);

  // Determine pager items needed.
    $pages = array();
    $c = $markers['pager_current'] - 1;
    $m = $markers['pager_max'] - 1;
    switch ($theme) {
    case 'pagerer_adaptive':



        // determine adaptive keys coming from query parameters
        $qps = drupal_get_query_parameters();
        if (isset($qps['page_ak'])) {
            $tmp = explode('.', $qps['page_ak']);
            $pl = $tmp[0];
            $pr = $tmp[1];
            $px = isset($tmp[2]) ? $tmp[2] : null;
        } else {
            list($pl, $pr, $px) = array(null, null, null);
        }
        // first
        $pages[0]['interval'] = -$c;
        $pages[0]['text'] = _pagerer_get_page_text($variables, $markers, -$c, $variables['tags']['previous']);
        // last
        $pages[$m]['interval'] = $m - $c;
        $pages[$m]['text'] = _pagerer_get_page_text($variables, $markers, $m - $c, $variables['tags']['next']);
        // neighborhood
        $nPages = _pagerer_get_neighborhood_pages($variables, $markers);
        // enrich neighborhood with adaptive markers
        if ($nPages) {
            foreach ($nPages as $page => &$page_data) {
                if (!is_null($px)) {
                    $page_data['page_pl'] = $pl;
                    $page_data['page_pr'] = $pr;
                    $page_data['page_px'] = $px;
                } else {
                    $page_data['page_pl'] = !is_null($pl) ? $pl : 0;
                    $page_data['page_pr'] = !is_null($pr) ? $pr : $m;
                    $page_data['page_px'] = $c;
                }
            }
        }
        $pages += $nPages;
        // progressives
        if (!is_null($pl)) {
            if (($pl > 0) and !isset($pages[$pl])) {
                $pages[$pl]['interval'] = -$markers['pager_current'] + $pl + 1;
                $pages[$pl]['text'] = _pagerer_get_page_text($variables, $markers, -$markers['pager_current'] + $pl + 1, $variables['tags']['previous_progr'], $variables['progr_links']);
                $pages[$pl]['progressive'] = true;
            }
            $l = $pl;
        } else {
            $l = 0;
        }
        if (!is_null($pr)) {
            if (($pr < $m)  and !isset($pages[$pr])) {
                $pages[$pr]['interval'] = $pr - $markers['pager_current'] + 1;
                $pages[$pr]['text'] = _pagerer_get_page_text($variables, $markers, $pr - $markers['pager_current'] + 1, $variables['tags']['next_progr'], $variables['progr_links']);
                $pages[$pr]['progressive'] = true;
            }
            $r = $pr;
        } else {
            $r =  $m;
        }
        if (!is_null($px)) {
            $x = $px;
        } else {
            $x = null;
        }
        // progressives
        $output = '';
        $pages += _pagerer_get_adaptive_pages(
            $variables,
            $markers,
            $pages,
            $l, $r, $x, $output
        );
        ksort($pages);
        // enrich progressives with adaptive markers
        if ($pages) {
            $kpages = array_keys($pages);
            for ($x = 1; $x < count($kpages) - 1; $x++) {
                $d = &$pages[$kpages[$x]];
                // attuale prog
                if (isset($pages[$kpages[$x]]['progressive'])) {
                    $d['page_pl'] = $kpages[$x - 1];
                    $d['page_pr'] = $kpages[$x + 1];
                }
            }
        }


    case 'pagerer_progressive':
        // first
        $pages[0]['interval'] = -$c;
        $pages[0]['text'] = _pagerer_get_page_text($variables, $markers, -$c, $variables['tags']['previous']);
        // last
        $pages[$m]['interval'] = $m - $c;
        $pages[$m]['text'] = _pagerer_get_page_text($variables, $markers, $m - $c, $variables['tags']['next']);
        // neighborhood
        $pages += _pagerer_get_neighborhood_pages($variables, $markers);
        // progressive
        if (!empty($variables['factors'])) {
            $factors = explode(',', $variables['factors']);
            foreach ($factors as $scaleFactor) {
                $pages = _pagerer_get_progressive_pages($variables, $markers, $pages, $scaleFactor, 10);
            }
        }
        ksort($pages);
        break;
    case 'pagerer_mini':
        // current
        $pages[$c]['interval'] = 0;
        $pages[$c]['text'] = _pagerer_get_page_text($variables, $markers, 0);
        break;
    case 'pagerer_standard':
    default:
        // neighborhood
        $pages += _pagerer_get_neighborhood_pages($variables, $markers);
    }

    // compose pager
    $items = array();
    // 1. left
    if ($variables['label_display'] == 'left') {
        $items[] = array(
          'class' => array('pager-item'),
          'data' => $variables['tags']['label'],
        );
    }
    if ($variables['max_display'] == 'left') {
        $items[] = array(
          'class' => array('pager-item'),
          'data' => t($variables['tags']['max'], array('@pages' => $markers['pager_max'], '@items' => $markers['pager_item_max'],)),
        );
    }
    // 2. first + previous links
    if ($variables['first_link'] == 'always' or ($variables['first_link'] == 'not_on_first' and $c <> 0)) {
        $items = array_merge($items, _pagerer_itemize_first_link($variables, $markers));
    }
    if ($variables['previous_link'] == 'always' or ($variables['previous_link'] == 'not_on_first' and $c <> 0)) {
        $items = array_merge($items, _pagerer_itemize_previous_link($variables, $markers));
    }
    // 3. pages
    $items =  array_merge($items, _pagerer_itemize_page_links($variables, $markers, $pages, ($theme == 'pagerer_mini' ? false : true)));
    // 4. next + last links
    if ($variables['next_link'] == 'always' or ($variables['next_link'] == 'not_on_last' and $c <> $m)) {
        $items = array_merge($items, _pagerer_itemize_next_link($variables, $markers));
    }
    if ($variables['last_link'] == 'always' or ($variables['last_link'] == 'not_on_last' and $c <> $m)) {
        $items = array_merge($items, _pagerer_itemize_last_link($variables, $markers));
    }
    // 5. right
    if ($variables['label_display'] == 'right') {
        $items[] = array(
          'class' => array('pager-item'),
          'data' => $variables['tags']['label'],
        );
    }
    if ($variables['max_display'] == 'right') {
        $items[] = array(
          'class' => array('pager-item'),
          'data' => t($variables['tags']['max'], array('@pages' => $markers['pager_max'], '@items' => $markers['pager_item_max'],)),
        );
    }

    // @todo remove
    $output = isset($output) ? $output : null;

    return $output. '<h2 class="element-invisible">' . t('Pages') . '</h2>' . theme('item_list', array(
        'items' => $items,
        'attributes' => array('class' => array('pager')),
    ));
}

/**
 * Direct page/item entry widget.
 *
 * Enables client side to directly enter a target page in an input box.
 *
 * @param array $variables theme's variables
 * @param array $markers   precalculated markers for the pager
 *
 * @return string HTML element representing the widget
 */
function _pagerer_widget($variables, $markers)
{
    global $pager_page_array, $pager_limits;

    drupal_add_js(drupal_get_path('module', 'pagerer') .'/pagerer.js');

    // prepare query parameters, overriding current 'page' with a text that the js widget will replace
    // with the content of HTML 'value' attribute
    $c = $markers['pager_current'] - 1;
    $page_new = pager_load_array($c, $variables['element'], $pager_page_array);
    $page_new[$variables['element']] = 'pagererpage';
    $variables['parameters']['page'] = implode(',', $page_new);
    $queryParameters = _pagerer_get_query_parameters();
    $variables['parameters'] += $queryParameters;

    // are we displaying pages or items; 'value' HTML attribute will bear the current $curr value;
    // $max is passed to the js widget to ensure input is not bigger
    if ($variables['display'] == 'pages') {
        $curr = $markers['pager_current'];
        $max = $markers['pager_max'];
        $interval = 1;
        $text = t('page');
    } else {
        $curr = $markers['pager_current_first_item'];
        $max = $markers['pager_item_max'];
        $interval = $pager_limits[$variables['element']];
        $text = t('item');
    }
    // clean urls
    if (!empty($GLOBALS['conf']['clean_url'])) {
        $path = $_GET['q'] . '?' . drupal_http_build_query($variables['parameters']);
    } else {
    // no clean urls
        $query = array('q' => $_GET['q']);
        $query += $variables['parameters'];
        $path = '?' . drupal_http_build_query($query);
    }
    // prepare js wdget state and title
    $state = drupal_json_encode(array(
        'url' => $path,
        'element' => $variables['element'],
        'total' => $max,
        'interval' => $interval,
        'display' => $variables['display']
    ));
    $title = t('Set @text number to go to, then press enter', array ('@text' => $text,));
    return "<input type=\"text\" class=\"pagerer-page\" name ='$state' title=\"$title\" value=\"$curr\" />";
}

/**
 * Helper to calculate some markers needed by all themes.
 *
 * @param array $variables theme's variables
 *
 * @return array associative array of integer values representing the markers
 */
function _pagerer_resolve_markers($variables)
{
    global $pager_page_array, $pager_total, $pager_total_items, $pager_limits;

    // Calculate various markers

    $markers = array();

    // Pages

    // Middle is used to "center" pages around the current page.
    $markers['pager_middle'] = ceil($variables['quantity'] / 2);
    // current is the page we are currently paged to
    $markers['pager_current'] = $pager_page_array[$variables['element']] + 1;
    // first is the first page listed by this pager piece (re quantity)
    $markers['pager_first'] = $markers['pager_current'] - $markers['pager_middle'] + 1;
    // last is the last page listed by this pager piece (re quantity)
    $markers['pager_last'] = $markers['pager_current'] + $variables['quantity'] - $markers['pager_middle'];
    // max is the maximum page number
    $markers['pager_max'] = $pager_total[$variables['element']];

    // Items

    // pager_current_first_item is the first item listed on the current page
    $markers['pager_current_first_item'] = $pager_limits[$variables['element']] * $pager_page_array[$variables['element']] + 1;
    // pager_current_last_item is the last item listed on the current page
    $markers['pager_current_last_item'] = ($pager_limits[$variables['element']] * $markers['pager_current']) > $pager_total_items[$variables['element']] ?
        $pager_total_items[$variables['element']] :
        $pager_limits[$variables['element']] * $markers['pager_current'];
    // pager_item_max is the maximum item number
    $markers['pager_item_max'] = $pager_total_items[$variables['element']];
    // pager_items_next is the number of items expected on next page
    if ($markers['pager_current'] * $pager_limits[$variables['element']] > $markers['pager_item_max']) {
        $markers['pager_items_next'] = null;
    } else {
        $markers['pager_items_next'] = $pager_total_items[$variables['element']] - ($markers['pager_current'] * $pager_limits[$variables['element']]) > $pager_limits[$variables['element']] ?
            $pager_limits[$variables['element']] :
            $pager_total_items[$variables['element']] - ($markers['pager_current'] * $pager_limits[$variables['element']]);
    }
    // pager_item_previous is the number of items expected on previous page
    if ($markers['pager_current'] == 1) {
        $markers['pager_items_previous'] = null;
    } else {
        $markers['pager_items_previous'] = $pager_limits[$variables['element']];
    }

    // End of marker calculations.

    return $markers;
}

/**
 * Return rendered items representing the link to "first" element in the pager.
 *
 * @param array $variables theme's variables
 * @param array $markers   precalculated markers for the pager
 *
 * @return array pre-rendered items
 */
function _pagerer_itemize_first_link($variables, $markers)
{
    $c = $markers['pager_current'] - 1;
    $text = _pagerer_get_page_text($variables, $markers, -$c, $variables['tags']['first']);
    $li_first = theme(
        'pager_first',
        array(
            'text' => t($variables['tags']['first'], array('@num' => $text)),
            'element' => $variables['element'],
            'parameters' => $variables['parameters'],
        )
    );
    $items = array();
    $items[] = array(
        'class' => array('pager-first'),
        'data' => $li_first ? $li_first : t($variables['tags']['first'], array('@num' => $text)),
    );
    $items[] = array(
        'class' => array('pager-item'),
        'data' => $variables['tags']['pager_separator'],
    );
    return $items;
}

/**
 * Return rendered items representing the link to "previous" element in the pager.
 *
 * @param array $variables theme's variables
 * @param array $markers   precalculated markers for the pager
 *
 * @return array pre-rendered items
 */
function _pagerer_itemize_previous_link($variables, $markers)
{
    $text = _pagerer_get_page_text($variables, $markers, -1, $variables['tags']['previous']);
    $li_previous = theme(
        'pager_previous',
        array(
            'text' => t($variables['tags']['previous'], array('@num' => $text)),
            'element' => $variables['element'],
            'interval' => 1,
            'parameters' => $variables['parameters'],
        )
    );
    $items = array();
    $items[] = array(
        'class' => array('pager-previous'),
        'data' => $li_previous ? $li_previous : t($variables['tags']['previous'], array('@num' => $text)),
    );
    $items[] = array(
        'class' => array('pager-item'),
        'data' => $variables['tags']['pager_separator'],
    );
    return $items;
}

/**
 * Return rendered items representing the link to "next" element in the pager.
 *
 * @param array $variables theme's variables
 * @param array $markers   precalculated markers for the pager
 *
 * @return array pre-rendered items
 */
function _pagerer_itemize_next_link($variables, $markers)
{
    $text = _pagerer_get_page_text($variables, $markers, 1, $variables['tags']['next']);
    $li_next = theme(
        'pager_next',
        array(
            'text' => t($variables['tags']['next'], array('@num' => $text)),
            'element' => $variables['element'],
            'interval' => 1,
            'parameters' => $variables['parameters']
        )
    );
    $items = array();
    $items[] = array(
        'class' => array('pager-item'),
        'data' => $variables['tags']['pager_separator'],
    );
    $items[] = array(
        'class' => array('pager-next'),
        'data' => $li_next ? $li_next : t($variables['tags']['next'], array('@num' => $text)),
    );
    return $items;
}

/**
 * Return rendered items representing the link to "last" element in the pager.
 *
 * @param array $variables theme's variables
 * @param array $markers   precalculated markers for the pager
 *
 * @return array pre-rendered items
 */
function _pagerer_itemize_last_link($variables, $markers)
{
    $c = $markers['pager_current'] - 1;
    $m = $markers['pager_max'] - 1;
    $text = _pagerer_get_page_text($variables, $markers, $m - $c, $variables['tags']['last']);
    $li_last = theme(
        'pager_last',
        array(
            'text' => t($variables['tags']['last'], array('@num' => $text)),
            'element' => $variables['element'],
            'parameters' => $variables['parameters']
        )
    );
    $items = array();
    $items[] = array(
        'class' => array('pager-item'),
        'data' => $variables['tags']['pager_separator'],
    );
    $items[] = array(
        'class' => array('pager-last'),
        'data' => $li_last ? $li_last : t($variables['tags']['last'], array('@num' => $text)),
    );
    return $items;
}

/**
 * Return rendered items representing the links to 'page' elements in the pager.
 *
 * @param array   $variables   theme's variables
 * @param array   $markers     precalculated markers for the pager
 * @param array   $pages       the pages that are to be displayed in the pager
 * @param boolean $fl_breakers if true, breakers are put before and after the pager's page list if
 *                             first/last page in the pager list do not coincide with overall first/last page
 *
 * @return array pre-rendered items
 */
function _pagerer_itemize_page_links($variables, $markers, $pages, $fl_breakers = true)
{
    $c = $markers['pager_current'] - 1;
    $m = $markers['pager_max'] - 1;
    $items = array();
    if (!empty($pages)) {
        $i = 0;
        $previous_page = null;
        foreach($pages as $page => $page_data) {
            // if not on first link, then introduce a separator or a breaker between the links
            if (isset($previous_page)) {
                if ($page == $previous_page + 1) {
                    $items[] = array(
                        'class' => array('pager-item'),
                        'data' => $variables['tags']['pager_separator'],
                    );
                } else {
                    $items[] = array(
                        'class' => array('pager-item'),
                        'data' => $variables['tags']['pager_breaker'],
                    );
                }
            }
            // if on first link, but current page is not first, introduce a breaker before the new link
            else if ($page <> 0 and $fl_breakers) {
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => $variables['tags']['pager_breaker'],
                );
            }
            // sets previous page
            $previous_page = $page;
            $text = $page_data['text'];
            // link to page before the current
            if ($page_data['interval'] < 0) {
                if (isset($page_data['page_pl'])) {
                    if (isset($page_data['page_px'])) {
                        $variables['parameters']['page_ak'] = implode('.', array($page_data['page_pl'], $page_data['page_pr'], $page_data['page_px']));
                    } else {
                        $variables['parameters']['page_ak'] = implode('.', array($page_data['page_pl'], $page_data['page_pr']));
                    }
                } else {
                    unset($variables['parameters']['page_ak']);
                }
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => theme(
                        'pager_previous',
                        array(
                            'text' => $text,
                            'element' => $variables['element'],
                            'interval' => -$page_data['interval'],
                            'parameters' => $variables['parameters']
                        )
                    ),
                );
            }
            // link to current page
            else if ($page_data['interval'] == 0) {
                if ($variables['label_display'] == 'before_current') {
                    $items[] = array(
                      'class' => array('pager-item'),
                      'data' => $variables['tags']['label'],
                    );
                }
                switch ($variables['current_display']) {
                case 'none':
                    break;
                case 'widget':
                    $items[] = array(
                       'class' => array('pager-current'),
                       'data' => _pagerer_widget($variables, $markers),
                    );
                    break;
                case 'normal':
                default:
                    $items[] = array(
                       'class' => array('pager-current'),
                       'data' => $text,
                    );
                }
                if ($variables['max_display'] == 'after_current') {
                    $items[] = array(
                      'class' => array('pager-item'),
                      'data' => t($variables['tags']['max'], array('@pages' => $markers['pager_max'], '@items' => $markers['pager_item_max'],)),
                    );
                }
            }
            // link to page after the current
            else if ($page_data['interval'] > 0){
                if (isset($page_data['page_pl'])) {
                    if (isset($page_data['page_px'])) {
                        $variables['parameters']['page_ak'] = implode('.', array($page_data['page_pl'], $page_data['page_pr'], $page_data['page_px']));
                    } else {
                        $variables['parameters']['page_ak'] = implode('.', array($page_data['page_pl'], $page_data['page_pr']));
                    }
                } else {
                    unset($variables['parameters']['page_ak']);
                }
                $items[] = array(
                    'class' => array('pager-item'),
                    'data' => theme(
                        'pager_next',
                        array(
                            'text' => $text,
                            'element' => $variables['element'],
                            'interval' => $page_data['interval'],
                            'parameters' => $variables['parameters']
                        )
                    ),
                );
            }
            $i++;
        }
        if (($page <> $m) and $fl_breakers) {
            $items[] = array(
                'class' => array('pager-item'),
                'data' => $variables['tags']['pager_breaker'],
            );
        }
    }
    return $items;
}

/**
 * Return an array of 'pages' in the neighborhood of the current one.
 *
 * This is in fact generating the same list of pages as standard Drupal pager. The neighborhood
 * is centered on the current page, with ($variables['quantity'] / 2) pages listed on left and right
 * of the current, provided there are enough pages.
 *
 * @param array   $variables   theme's variables
 * @param array   $markers     precalculated markers for the pager
 *
 * @return array associative array of pages, with key = page and value an array having 'text' and 'interval'
 *               (the offset from current page) keys/values
 */
function _pagerer_get_neighborhood_pages($variables, $markers)
{
    global $pager_limits;

    // Prepare for generation loop.
    $i = $markers['pager_first'];
    if ($markers['pager_last'] > $markers['pager_max']) {
    // Adjust "center" if at end of query.
        $i = $i + ($markers['pager_max'] - $markers['pager_last']);
        $markers['pager_last'] = $markers['pager_max'];
    }
    if ($i <= 0) {
    // Adjust "center" if at start of query.
        $markers['pager_last'] = $markers['pager_last'] + (1 - $i);
        $i = 1;
    }
    // End of generation loop preparation.

    $pages = array();
    $c = $markers['pager_current'] - 1;
    $m = $markers['pager_max'] - 1;
    for (; $i <= $markers['pager_last'] && $i <= $markers['pager_max']; $i++) {
        $offset = $i - $markers['pager_current'];
        $pages[$i - 1]['interval'] = $offset;
        $pages[$i - 1]['text'] = _pagerer_get_page_text($variables, $markers, $offset);
    }
    return $pages;
}

/**
 * Return an array of 'pages' progressively more distant from current.
 *
 * @param array   $variables    theme's variables
 * @param array   $markers      precalculated markers for the pager
 * @param array   $pages        array of pages already enlisted, to prevent override
 * @param integer $scale_factor scale factor to be used in the progressive series
 * @param integer $ratio        ratio to be used in the progressive series
 * @param integer $limit        (optional) to be used to limit the quantity of pages enlisted
 *
 * @return array associative array of pages, with key = page and value an array having 'text' and 'interval'
 *               (the offset from current page) keys/values; a key 'progressive' set to true is also added as
 *               a marker
 */
function _pagerer_get_progressive_pages($variables, $markers, $pages, $scale_factor, $ratio, $limit = null)
{
    global $pager_limits;

    // avoid endless loop in converging series
    if ($ratio < 1) {
        $ratio = 1;
    }
    $offset = 0;
    $c = $markers['pager_current'] - 1;
    $m = $markers['pager_max'] - 1;
    for ($i = 0; ; $i++) {
        // breaks if limit reached
        if ($limit and $i > $limit - 1) {
            break;
        }
        // offset for this cycle
        $offset = intval($scale_factor * pow($ratio, $i));
        // breaks if offset > than total pages
        if ($offset > $markers['pager_max']) {
            break;
        }
        // negative offset
        if ($c - $offset > 0
            and !isset($pages[$c - $offset])){
            $pages[$c - $offset]['progressive'] = true;
            $pages[$c - $offset]['interval'] = -$offset;
            $pages[$c - $offset]['text'] = _pagerer_get_page_text($variables, $markers, -$offset, $variables['tags']['previous_progr'], $variables['progr_links']);
        }
        // positive offset
        if ($c + $offset < $markers['pager_max']
            and !isset($pages[$c + $offset])) {
            $pages[$c + $offset]['progressive'] = true;
            $pages[$c + $offset]['interval'] = $offset;
            $pages[$c + $offset]['text'] = _pagerer_get_page_text($variables, $markers, $offset, $variables['tags']['next_progr'], $variables['progr_links']);
        }
    }
    return $pages;
}

function _pagerer_get_adaptive_pages($variables, $markers, $pages, $l, $r, $x, &$output)
{
    global $pager_limits;

    $c = $markers['pager_current'] - 1;
    $m = $markers['pager_max'] - 1;
    $x = is_null($x) ? $c : $x;
    $output .= "c=$c x=$x l=$l r=$r <br/>";

    $sl = $x - $l;
    $sr = $r - $x;
    $m  = max($sl, $sr) / 2;
    $output .= "sl=$sl sr=$sr m=$m  <br/>";
    for ($i = 0; $i < 2; $i++) {
        $off = intval($m * pow(0.5, $i));
        $p = $x - $off;
        // negative offset
        if ($p > $l
            and !isset($pages[$p])) {
            $output .= "neg off=$off p=$p <br/>";
            $pages[$p]['progressive'] = true;
            $pages[$p]['interval'] = $p - $c;
            $pages[$p]['text'] = _pagerer_get_page_text($variables, $markers, $p - $c, $variables['tags']['previous_progr'], $variables['progr_links']);
        }
        // positive offset
        $p = $x + $off;
        if ($p < $r //$markers['pager_max']
            and !isset($pages[$p])){
            $output .= "pos off=$off p=$p <br/>";
            $pages[$p]['progressive'] = true;
            $pages[$p]['interval'] = $p - $c;
            $pages[$p]['text'] = _pagerer_get_page_text($variables, $markers, $p - $c, $variables['tags']['next_progr'], $variables['progr_links']);
        }
    }
    return $pages;
}

/**
 * Return textual element for a 'page' element in the pager.
 *
 * Value returned is dependent on what's being displayed in the pager via the
 * $variable['display'] and the $mode selected ['absolute'|'relative'].
 *
 * @param array   $variables theme's variables
 * @param array   $markers   precalculated markers for the pager
 * @param integer $offset    offset of page to be rendered, from current page
 * @param string  $tag       tag to be used to render the text
 * @param string  $mode      ['absolute'|'relative']
 *                           - 'absolute' returns the page/item/item range at offset
 *                           - 'relative' returns the offset (pages/items) from current
 *
 * @return string fully qualified page text
 */
function _pagerer_get_page_text($variables, $markers, $offset, $tag = '@num', $mode = 'absolute')
{
    global $pager_limits;

    $c = $markers['pager_current'] - 1;
    $m = $markers['pager_max'] - 1;

    switch ($mode) {
    case 'relative':
        switch ($variables['display']) {
        case 'item_ranges':
        case 'items':
            $text = t($tag, array ('@num' => abs($offset * $pager_limits[$variables['element']])));
            break;
        case 'pages':
        default:
            $text = t($tag, array ('@num' => abs($offset)));
            break;
        }
        break;
    case 'absolute':
    default:
        switch ($variables['display']) {
        case 'item_ranges':
            $max = min(($c + $offset + 1) * $pager_limits[$variables['element']], $markers['pager_item_max']);
            $text =   (($c + $offset) * $pager_limits[$variables['element']] + 1)
                       . $variables['tags']['range_separator']
                       . ($max);
            break;
        case 'items':
            $text = ($c + $offset) * $pager_limits[$variables['element']] + 1;
            break;
        case 'pages':
        default:
            $text = $c + $offset + 1;
            break;
        }
        break;
    }
    return $text;
}

